<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>GfxRip.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="GfxRip.ico" />
  </ItemGroup>

</Project>
